#include "service_surface.h"

#include <algorithm>
#include <format>
#include <sstream>

namespace dao::playground {

auto find_service_shape(std::string_view name) -> const ShapeSpec* {
  auto it = std::ranges::find(kServiceShapes, name, &ShapeSpec::name);
  return it != kServiceShapes.end() ? &*it : tooling::find_shape(name);
}

auto find_route(std::string_view name) -> const RouteSpec* {
  auto it = std::ranges::find(kRoutes, name, &RouteSpec::name);
  return it == kRoutes.end() ? nullptr : &*it;
}

auto render_service_typescript() -> std::string {
  std::ostringstream out;
  out << "// Generated by service_surface_dump from compiler/analysis/tooling_surface.h\n"
         "// (semantic kinds and analysis payload shapes) and\n"
         "// tools/playground/compiler_service/service_surface.h (envelopes and routes).\n"
         "// Do not edit by hand: change a table and run `task gen-tooling-surface`.\n"
         "// service_test fails while this file and the tables disagree.\n\n";

  out << tooling::render_analysis_typescript();

  out << "// ---- Service envelopes ----\n\n";
  for (const auto& shape : kServiceShapes) {
    tooling::render_shape_typescript(out, shape);
  }

  out << "export const ROUTES = {\n";
  for (const auto& route : kRoutes) {
    out << std::format(
        "  {}: {{ method: \"{}\", path: \"{}\" }},\n", route.name, route.method, route.path);
  }
  out << "} as const;\n\n"
         "export type RouteName = keyof typeof ROUTES;\n\n";

  out << "/** Request body and response type of every route. */\n"
         "export interface RouteTypes {\n";
  for (const auto& route : kRoutes) {
    out << std::format(
        "  {}: {{ request: {}; response: {} }};\n", route.name, route.request, route.response);
  }
  out << "}\n";
  return out.str();
}

} // namespace dao::playground
